version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cagen_quota
      POSTGRES_USER: quota_user
      POSTGRES_PASSWORD: quota_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quota_user -d cagen_quota"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Cagen Quota Service
  quota-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://quota_user:quota_password@postgres:5432/cagen_quota?sslmode=disable
      PORT: 8080
      GIN_MODE: debug
      ENVIRONMENT: development
      AUTH_SERVICE_URL: https://cagen-auth-service-production.up.railway.app
      QUOTA_SERVICE_ID: svc_cagen_quota
      LOG_LEVEL: info
      LOG_FORMAT: text
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data: